name: D2b

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Data2bot
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f configs/requirements.txt ]; then pip install -r configs/requirements.txt; fi
    - name: Run pipe
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python scripts/start.py
    - name: publish doc
      run: |
        pip install mkdocs-material 
        mkdocs gh-deploy --force
